create database mysql_prog_web;

use mysql_prog_web;

CREATE TABLE USERS (
ID INTEGER NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(254) NOT NULL,
PASS VARCHAR(255) NOT NULL, #PASSWORD
PRIMARY KEY (ID),
UNIQUE (USERNAME),
UNIQUE (EMAIL));


CREATE TABLE SHOPS (
ID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(32000),
WEB_SITE_URL VARCHAR(255),
GLOBAL_VALUE INTEGER,
ID_OWNER INTEGER,
ID_CREATOR INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_OWNER) REFERENCES USERS (ID),
FOREIGN KEY (ID_CREATOR) REFERENCES USERS (ID),
CONSTRAINT GLOBAL_VALUE_CHECK CHECK (GLOBAL_VALUE >= 0 AND GLOBAL_VALUE <= 5));


CREATE TABLE COORDINATES (
ID INTEGER NOT NULL AUTO_INCREMENT,
LATITUDE FLOAT NOT NULL,
LONGITUDE FLOAT NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));



CREATE TABLE SHOP_COORDINATE (
ID_SHOP INTEGER NOT NULL,
ID_COORDINATE INTEGER NOT NULL,
PRIMARY KEY (ID_SHOP, ID_COORDINATE),
FOREIGN KEY (ID_SHOP) REFERENCES SHOPS (ID),
FOREIGN KEY (ID_COORDINATE) REFERENCES COORDINATES (ID)); 


CREATE TABLE PRODUCTS (
ID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(32000) NOT NULL,
PRICE FLOAT,
ID_SHOP INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_SHOP) REFERENCES SHOPS (ID)); 


CREATE TABLE PICTURES (
ID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR (32000),
PATH VARCHAR(255) NOT NULL,
ID_PRODUCT INTEGER NOT NULL,
ID_OWNER INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID),
FOREIGN KEY (ID_OWNER) REFERENCES USERS (ID));


CREATE TABLE REVIEWS (
ID INTEGER NOT NULL AUTO_INCREMENT,
GLOBAL_VALUE INTEGER NOT NULL,
 CONSTRAINT REVIEW_GLOBAL_VALUE_CHECK CHECK (GLOBAL_VALUE >= 1 AND GLOBAL_VALUE <= 5),
QUALITY INTEGER,
 CONSTRAINT REVIEW_QUALITY_CHECK CHECK (QUALITY IS NULL OR (QUALITY >= 1 AND QUALITY <= 5)),
SERVICE INTEGER,
 CONSTRAINT REVIEW_SERVICE_CHECK CHECK (SERVICE IS NULL OR (SERVICE >= 1 AND SERVICE <= 5)),
VALUE_FOR_MONEY INTEGER,
 CONSTRAINT REVIEW_VALUE_FOR_MONEY_CHECK CHECK (VALUE_FOR_MONEY IS NULL OR (VALUE_FOR_MONEY >= 1 AND VALUE_FOR_MONEY <= 5)),
NAME VARCHAR(25),
DESCRIPTION VARCHAR(32000),
DATE_CREATION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ID_PRODUCT INTEGER NOT NULL,
ID_CREATOR INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID),
FOREIGN KEY (ID_CREATOR) REFERENCES USERS (ID));

#------------------------------------------------------------------------------
#4 aree geografiche, ognuna con 5 città
#5 citta, ognuna con 10 negozi. 
#per ogni città almeno 20 recensioni 
























